/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : Cpu.c
**     Project     : KL27Chainsaw
**     Processor   : MKL27Z64VLH4
**     Component   : MKL27Z64LH4
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Datasheet   : KL27P64M48SF2RM, Rev. 1, Sep 2014
**     Compiler    : Keil ARM C/C++ Compiler
**     Date/Time   : 2016-11-26, 16:08, # CodeGen: 53
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         SystemInit            - void SystemInit(void);
**         SystemCoreClockUpdate - void SystemCoreClockUpdate(void);
**
**     (c) Freescale Semiconductor, Inc.
**     2004 All Rights Reserved
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Cpu.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup Cpu_module Cpu module documentation
**  @{
*/         

/* MODULE Cpu. */

/* {Default RTOS Adapter} No RTOS includes */
#include "Cpu.h"
#include "Events.h"


#ifdef __cplusplus
extern "C" {
#endif

/*
** ===================================================================
**     Method      :  Common_Init (component MKL27Z64LH4)
**     Description :
**         Initialization of registers for that there is no 
**         initialization component.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMMON_INIT
void Common_Init(void)
{
  /* This function contains initialization code which is not part of initialization 
     methods of peripheral initialization (Init) components used in the project.  
     This function is generated depending on Init components present 
     in the project. To remove initialization of a register from the Common_Init() 
     add Init component that includes initialization of this register.
     This function is also affected by after reset value optimization property 
     available in Component view\Generator_Configurations\Active configuration\
     Optimizations\Utilize after reset values. */
  /* Enable clock gate of peripherals initialized in Common_Init() */
  /* SIM_SCGC5: PORTB=1,PORTA=1 */
  SIM_SCGC5 |= (SIM_SCGC5_PORTB_MASK | SIM_SCGC5_PORTA_MASK);

  /* SIM_SCGC5: PORTB=1,PORTA=1 */
  SIM_SCGC5 |= (SIM_SCGC5_PORTB_MASK | SIM_SCGC5_PORTA_MASK);
  /* PORTA_PCR13: ISF=0,IRQC=0,DSE=0,PFE=0,PE=1 */
  PORTA_PCR13 = (uint32_t)((PORTA_PCR13 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_IRQC(0x0F) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_PFE_MASK
                )) | (uint32_t)(
                 PORT_PCR_PE_MASK
                ));
  /* PORTB_PCR18: ISF=0,IRQC=0,DSE=0,PFE=0,PE=1 */
  PORTB_PCR18 = (uint32_t)((PORTB_PCR18 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_IRQC(0x0F) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_PFE_MASK
                )) | (uint32_t)(
                 PORT_PCR_PE_MASK
                ));
  /* PORTB_PCR19: ISF=0,IRQC=0,DSE=0,PFE=0,PE=1 */
  PORTB_PCR19 = (uint32_t)((PORTB_PCR19 & (uint32_t)~(uint32_t)(
                 PORT_PCR_ISF_MASK |
                 PORT_PCR_IRQC(0x0F) |
                 PORT_PCR_DSE_MASK |
                 PORT_PCR_PFE_MASK
                )) | (uint32_t)(
                 PORT_PCR_PE_MASK
                ));

  /* Disable clock gate of peripherals initialized in Common_Init() */
}

#endif /* CPU_COMMON_INIT */
/*
** ===================================================================
**     Method      :  Components_Init (component MKL27Z64LH4)
**     Description :
**         Initialization of components (with exception for Peripheral
**         Initialization Components which are initialized in 
**         Peripherals_Init() method).
**         For example, if automatic initialization feature 
**         is enabled in LDD component then its Init method call 
**         is executed in Components_Init() method.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#if CPU_COMPONENTS_INIT
void Components_Init(void)
{

  /*! tpmTmr1 Auto initialization start */
  NVIC_SetPriority(TPM0_IRQn, 1U);
  TPM_DRV_Init(tpmTmr1_IDX, &tpmTmr1_InitConfig0);
  TPM_DRV_SetClock(tpmTmr1_IDX, kTpmClockSourceModuleClk, kTpmDividedBy16);
  TPM_DRV_CounterStart(tpmTmr1_IDX, kTpmCountingUp, 20000U,true);      
  /*! tpmTmr1 Auto initialization end */
  
  /*! tpmTmr2 Auto initialization start */
  TPM_DRV_Init(tpmTmr2_IDX, &tpmTmr2_InitConfig0);
  TPM_DRV_SetClock(tpmTmr2_IDX, kTpmClockSourceModuleClk, kTpmDividedBy1);
  TPM_DRV_PwmStart(tpmTmr2_IDX, &tpmTmr2_ChnConfig0, 0U);
  /*! tpmTmr2 Auto initialization end */
  
  /*! tpmTmr3 Auto initialization start */
  NVIC_SetPriority(TPM2_IRQn, 0U);
  TPM_DRV_Init(tpmTmr3_IDX, &tpmTmr3_InitConfig0);
  TPM_DRV_SetClock(tpmTmr3_IDX, kTpmClockSourceModuleClk, kTpmDividedBy128);
  TPM_DRV_InputCaptureEnable(tpmTmr3_IDX, 0U, kTpmRisingEdge, 65535U, true);          
  /*! tpmTmr3 Auto initialization end */
  
  /*! adConv1 Auto initialization start */
  ADC16_DRV_Init(adConv1_IDX, &adConv1_InitConfig0);
  ADC16_DRV_ConfigConvChn(adConv1_IDX, 0U, &adConv1_ChnConfig0);
  /*! adConv1 Auto initialization end */

  /*! gpio4 Auto initialization start */
  NVIC_SetPriority(PORTBCDE_IRQn, 0U);
  GPIO_DRV_Init(gpio4_InpConfig0,gpio4_OutConfig0);
  /*! gpio4 Auto initialization end */
  
}
#endif /* CPU_COMPONENTS_INIT */


#ifdef __cplusplus
}
#endif

/* END Cpu. */

