/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : GPIOB_Config.h
**     Project     : KL27Chainsaw
**     Processor   : MKL27Z64VLH4
**     Component   : Init_GPIO
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : Keil ARM C/C++ Compiler
**     Date/Time   : 2016-11-11, 13:48, # CodeGen: 5
**     Abstract    :
**          This file implements the GPIO (GPIOB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : GPIOB
**          Device                                         : GPIOB
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Pin 0                                        : Do not initialize
**            Pin 1                                        : Do not initialize
**            Pin 2                                        : Do not initialize
**            Pin 3                                        : Do not initialize
**            Pin 16                                       : Do not initialize
**            Pin 17                                       : Do not initialize
**            Pin 18                                       : Initialize
**              Pin direction                              : Output
**              Output value                               : 1
**              Pull resistor                              : Enabled
**              Pull selection                             : <Automatic>
**              Slew rate                                  : <Automatic>
**              Drive strength                             : <Automatic>
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**            Pin 19                                       : Initialize
**              Pin direction                              : Output
**              Output value                               : 1
**              Pull resistor                              : Enabled
**              Pull selection                             : <Automatic>
**              Slew rate                                  : <Automatic>
**              Drive strength                             : <Automatic>
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**          Pin selection/routing                          : 
**            Pin 0                                        : Disabled
**            Pin 1                                        : Disabled
**            Pin 2                                        : Disabled
**            Pin 3                                        : Disabled
**            Pin 16                                       : Disabled
**            Pin 17                                       : Disabled
**            Pin 18                                       : Enabled
**              Pin                                        : LEDRGB_RED/J2_11
**            Pin 19                                       : Enabled
**              Pin                                        : LEDRGB_GREEN/J2_13
**          Interrupts                                     : 
**            Port interrupt                               : Disabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void GPIOB_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file GPIOB_Config.h                                                  
** @version 01.08
** @brief
**          This file implements the GPIO (GPIOB) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup GPIOB_Config_module GPIOB_Config module documentation
**  @{
*/         

#ifndef GPIOB_Config_H_
#define GPIOB_Config_H_

/* MODULE GPIOB. */

/* GPIOB_PSOR: PTSO|=0x000C0000 */
#define GPIOB_PSOR_VALUE     0x000C0000U
#define GPIOB_PSOR_MASK      0x000C0000U
/* GPIOB_PCOR: PTCO&=~0x000C0000 */
#define GPIOB_PCOR_VALUE     0x00U
#define GPIOB_PCOR_MASK      0x000C0000U
/* GPIOB_PDDR: PDD|=0x000C0000 */
#define GPIOB_PDDR_VALUE     0x000C0000U
#define GPIOB_PDDR_MASK      0x000C0000U



#define GPIOB_AUTOINIT

/* END GPIOB. */
#endif /* #ifndef __GPIOB_Config_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
