/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : GPIOA.h
**     Project     : KL27Chainsaw
**     Processor   : MKL27Z64VLH4
**     Component   : Init_GPIO
**     Version     : Component 01.008, Driver 01.08, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : Keil ARM C/C++ Compiler
**     Date/Time   : 2016-11-11, 11:59, # CodeGen: 1
**     Abstract    :
**          This file implements the GPIO (GPIOA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
**     Settings    :
**          Component name                                 : GPIOA
**          Device                                         : GPIOA
**          Settings                                       : 
**            Clock gate                                   : Enabled
**            Pin 0                                        : Do not initialize
**            Pin 1                                        : Do not initialize
**            Pin 2                                        : Do not initialize
**            Pin 3                                        : Do not initialize
**            Pin 4                                        : Do not initialize
**            Pin 5                                        : Do not initialize
**            Pin 12                                       : Do not initialize
**            Pin 13                                       : Initialize
**              Pin direction                              : Output
**              Output value                               : 1
**              Pull resistor                              : Enabled
**              Pull selection                             : <Automatic>
**              Slew rate                                  : <Automatic>
**              Drive strength                             : <Automatic>
**              Interrupt/DMA request                      : <Automatic>
**              Passive filter                             : <Automatic>
**            Pin 18                                       : Do not initialize
**            Pin 19                                       : Do not initialize
**            Pin 20                                       : Do not initialize
**          Pin selection/routing                          : 
**            Pin 0                                        : Disabled
**            Pin 1                                        : Disabled
**            Pin 2                                        : Disabled
**            Pin 3                                        : Disabled
**            Pin 4                                        : Disabled
**            Pin 5                                        : Disabled
**            Pin 12                                       : Disabled
**            Pin 13                                       : Enabled
**              Pin                                        : LEDRGB_BLUE/J1_10
**            Pin 18                                       : Disabled
**            Pin 19                                       : Disabled
**            Pin 20                                       : Disabled
**          Interrupts                                     : 
**            Port interrupt                               : Disabled
**          Initialization                                 : 
**            Call Init method                             : yes
**            Utilize after reset values                   : default
**     Contents    :
**         Init - void GPIOA_Init(void);
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file GPIOA.h
** @version 01.08
** @brief
**          This file implements the GPIO (GPIOA) module initialization
**          according to the Peripheral Initialization settings, and
**          defines interrupt service routines prototypes.
*/         
/*!
**  @addtogroup GPIOA_module GPIOA module documentation
**  @{
*/         

#ifndef GPIOA_H_
#define GPIOA_H_

/* MODULE GPIOA. */

#include "GPIOA_Init.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Initialization method user name */
#define GPIOA_Init GPIOA_Init
/* PDD macros peripheral base address parameter */
#define GPIOA_DEVICE GPIOA_BASE_PTR

#ifdef __cplusplus
}
#endif

/* END GPIOA. */
#endif /* #ifndef __GPIOA_H_ */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/


