/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_init.c
**     Project     : KL27Chainsaw
**     Processor   : MKL27Z64VLH4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : Keil ARM C/C++ Compiler
**     Date/Time   : 2016-11-26, 13:34, # CodeGen: 51
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_init
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL27Z64LH4
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  DM0 - Differential minus channel 0     : <Automatic>
**                  DM3 - Differential minus channel 3     : <Automatic>
**                  DP0 - Differential plus channel 0      : <Automatic>
**                  DP1 - Differential plus channel 1      : <Automatic>
**                  DP3 - Differential plus channel 3      : <Automatic>
**                  SE0 - Single-ended channel 0           : <Automatic>
**                  SE1 - Single-ended channel 1           : <Automatic>
**                  SE3 - Single-ended channel 3           : <Automatic>
**                  SE8 - Single-ended channel 8           : <Automatic>
**                  SE9 - Single-ended channel 9           : <Automatic>
**                  SE11 - Single-ended channel 11         : <Automatic>
**                  SE12 - Single-ended channel 12         : <Automatic>
**                  SE13 - Single-ended channel 13         : <Automatic>
**                  SE14 - Single-ended channel 14         : <Automatic>
**                  SE15 - Single-ended channel 15         : <Automatic>
**                  SE23 - Single-ended channel 23         : <Automatic>
**                  SE4a - Single-ended channel 4a         : <Automatic>
**                  SE7a - Single-ended channel 7a         : <Automatic>
**                  SE4b - Single-ended channel 4b         : <Automatic>
**                  SE5b - Single-ended channel 5b         : <Automatic>
**                  SE6b - Single-ended channel 6b         : <Automatic>
**                  SE7b - Single-ended channel 7b         : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high                 : VDDA
**                  Voltage reference high                 : VREFH/VREF_OUT
**                  Voltage reference low                  : VREFL
**                  Voltage reference low                  : VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  IN0 - Input 0                          : <Automatic>
**                  IN1 - Input 1                          : <Automatic>
**                  IN2 - Input 2                          : <Automatic>
**                  IN3 - Input 3                          : <Automatic>
**                  IN4 - Input 4                          : <Automatic>
**                  IN5 - Input 5                          : <Automatic>
**                  OUT - Output                           : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CRC                        : 
**                Custom name                              : CRC
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  CLK - Clock                            : <Automatic>
**                  DIO - Data input/output                : <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DAC                        : 
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX0
**              Peripheral Type DWT                        : 
**              Peripheral Type FLEXIO                     : 
**                Custom name                              : FLEXIO
**                FLEXIO                                   : 
**                  D0 - Data pin 0                        : <Automatic>
**                  D1 - Data pin 1                        : <Automatic>
**                  D2 - Data pin 2                        : <Automatic>
**                  D3 - Data pin 3                        : <Automatic>
**                  D4 - Data pin 4                        : <Automatic>
**                  D5 - Data pin 5                        : <Automatic>
**                  D6 - Data pin 6                        : <Automatic>
**                  D7 - Data pin 7                        : <Automatic>
**                Bool_FLEXIO                              : yes
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 12                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 13                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 17                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 18                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 19                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 8                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 9                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 10                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 11                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 2                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 3                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 4                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 5                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 6                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 7                                  : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  Pin 0                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 1                                  : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 16                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 20                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 21                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 22                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 23                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 24                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 25                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 29                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 30                                 : <Automatic>
**                  Direction                              : <Automatic>
**                  Pin 31                                 : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C0                                : yes
**                Custom name                              : I2C1
**                I2C1                                     : 
**                  SCL - Serial clock                     : <Automatic>
**                  SDA - Serial data                      : <Automatic>
**                Bool_I2C1                                : yes
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  P5 - Wake-up pin 5                     : <Automatic>
**                  P6 - Wake-up pin 6                     : <Automatic>
**                  P7 - Wake-up pin 7                     : <Automatic>
**                  P8 - Wake-up pin 8                     : <Automatic>
**                  P9 - Wake-up pin 9                     : <Automatic>
**                  P10 - Wake-up pin 10                   : <Automatic>
**                  P14 - Wake-up pin 14                   : <Automatic>
**                  P15 - Wake-up pin 15                   : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  ALT0 - Pulse counter input 0           : <Automatic>
**                  ALT1 - Pulse counter input 1           : <Automatic>
**                  ALT2 - Pulse counter input 2           : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type LPUART                     : 
**                Custom name                              : LPUART0
**                LPUART0                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART0                             : yes
**                Custom name                              : LPUART1
**                LPUART1                                  : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_LPUART1                             : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  External clock/Oscillator input        : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type RFSYS                      : 
**                Custom name                              : RFSYS
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  CLKIN - Clock input                    : <Automatic>
**                  CLKOUT - Oscillator output             : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  NMI - Non-maskable interrupt           : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Trace clock output                     : <Automatic>
**                  ERCLK32K clock output                  : <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**                Custom name                              : SPI1
**                SPI1                                     : 
**                  MISO - Master data in, slave data out  : <Automatic>
**                  Direction                              : <Automatic>
**                  MOSI - Master data out, slave data in  : <Automatic>
**                  Direction                              : <Automatic>
**                  SCK - Serial clock                     : <Automatic>
**                  Direction                              : <Automatic>
**                  SS - Slave select                      : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI1                                : yes
**              Peripheral Type SUPPLY                     : 
**                SUPPLY                                   : 
**                  Chip power supply                      : VDD3
**                  Chip power supply                      : VDD36
**                  Chip power supply                      : VDD54
**                  Analog power supply                    : VDDA
**                  Chip ground                            : VSS4
**                  Chip ground                            : VSS37
**                  Chip ground                            : VSS53
**                  Analog ground                          : VSSA
**                Bool_SUPPLY                              : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH2 - Channel 2                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH3 - Channel 3                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH4 - Channel 4                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH5 - Channel 5                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM1                                : yes
**                Custom name                              : TPM2
**                TPM2                                     : 
**                  CH0 - Channel 0                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CH1 - Channel 1                        : <Automatic>
**                  Direction                              : <Automatic>
**                  CLKIN - External clock input           : <Automatic>
**                Bool_TPM2                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART2
**                UART2                                    : 
**                  RX - Receive data                      : <Automatic>
**                  TX - Transmit data                     : <Automatic>
**                Bool_UART2                               : yes
**              Peripheral Type USB                        : 
**                Custom name                              : USB0
**                USB0                                     : 
**                  CLKIN - Alternate Clock                : <Automatic>
**                  DM - Data minus                        : USB0_DM
**                  DP - Data plus                         : USB0_DP
**                  SOF - Start of frame                   : <Automatic>
**                  Power input                            : USB_VDD
**                Bool_USB0                                : yes
**              Peripheral Type VREF                       : 
**                Custom name                              : VREF
**                VREF                                     : 
**                  OUT - Voltage reference output         : VREFH/VREF_OUT
**                Bool_VREF                                : yes
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTE0/CLKOUT32K/SPI1_MISO/LPUART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA: 
**                Custom name, Signal name                 : J3_1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 2: PTE1/SPI1_MOSI/LPUART1_RX/SPI1_MISO/I2C1_SCL: 
**                Custom name, Signal name                 : ACCEL_RST/J3_3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 3: VDD3                                : 
**                Custom name, Signal name                 : VDD3
**              Pin 4: VSS4                                : 
**                Custom name, Signal name                 : VSS4
**              Pin 5: USB0_DP                             : 
**                Custom name, Signal name                 : USB0_DP
**              Pin 6: USB0_DM                             : 
**                Custom name, Signal name                 : USB0_DM
**              Pin 7: USB_VDD                             : 
**                Custom name, Signal name                 : USB_VDD
**              Pin 8: ADC0_DP1/ADC0_SE1/PTE16/SPI0_PCS0/UART2_TX/TPM_CLKIN0/FXIO0_D0: 
**                Custom name, Signal name                 : J4_2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 9: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/LPUART0_TX/FXIO0_D4: 
**                Custom name, Signal name                 : J4_6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 10: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/LPUART0_RX/FXIO0_D5: 
**                Custom name, Signal name                 : J4_8
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 11: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX/FXIO0_D6: 
**                Custom name, Signal name                 : THER_P
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 12: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX/FXIO0_D7: 
**                Custom name, Signal name                 : THER_N
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 13: VDDA                               : 
**                Custom name, Signal name                 : VDDA
**              Pin 14: VREFH/VREF_OUT                     : 
**                Custom name, Signal name                 : VREFH/VREF_OUT
**              Pin 15: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 16: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 17: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0: 
**                Custom name, Signal name                 : TOUCH_SLIDER_A
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 18: ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1/LPUART1_TX/LPTMR0_ALT1: 
**                Custom name, Signal name                 : TOUCH_SLIDER_B
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 19: PTE31/TPM0_CH4                     : 
**                Custom name, Signal name                 : J2_2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 20: PTE24/TPM0_CH0/I2C0_SCL            : 
**                Custom name, Signal name                 : J1_12
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 21: PTE25/TPM0_CH1/I2C0_SDA            : 
**                Custom name, Signal name                 : J1_8
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 22: PTA0/TPM0_CH5/SWD_CLK              : 
**                Custom name, Signal name                 : SWD_CLK
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 23: PTA1/LPUART0_RX/TPM2_CH0           : 
**                Custom name, Signal name                 : DBG_CONSOLE_RX/J1_2
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 24: PTA2/LPUART0_TX/TPM2_CH1           : 
**                Custom name, Signal name                 : DBG_CONSOLE_TX/J1_4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 25: PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO     : 
**                Custom name, Signal name                 : SWD_DIO
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 26: PTA4/I2C1_SDA/TPM0_CH1/NMI_b       : 
**                Custom name, Signal name                 : BUTTON_SW1/J2_5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 27: PTA5/USB_CLKIN/TPM0_CH2            : 
**                Custom name, Signal name                 : J2_4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 28: PTA12/TPM1_CH0                     : 
**                Custom name, Signal name                 : J1_6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 29: PTA13/TPM1_CH1                     : 
**                Custom name, Signal name                 : LEDRGB_BLUE/J1_10
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 30: VDD36                              : 
**                Custom name, Signal name                 : VDD36
**              Pin 31: VSS37                              : 
**                Custom name, Signal name                 : VSS37
**              Pin 32: EXTAL0/PTA18/LPUART1_RX/TPM_CLKIN0 : 
**                Custom name, Signal name                 : EXTAL_32KHZ
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 33: XTAL0/PTA19/LPUART1_TX/TPM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL_32KHZ
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 34: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : BUTTON_SW2/RESET
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 35: ADC0_SE8/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0/SPI1_MOSI/SPI1_MISO: 
**                Custom name, Signal name                 : J4_12
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 36: ADC0_SE9/PTB1/I2C0_SDA/TPM1_CH1/SPI1_MISO/SPI1_MOSI: 
**                Custom name, Signal name                 : J4_10
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 37: ADC0_SE12/PTB2/I2C0_SCL/TPM2_CH0   : 
**                Custom name, Signal name                 : J1_15
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 38: ADC0_SE13/PTB3/I2C0_SDA/TPM2_CH1   : 
**                Custom name, Signal name                 : J1_13
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 39: PTB16/SPI1_MOSI/LPUART0_RX/TPM_CLKIN0/SPI1_MISO: 
**                Custom name, Signal name                 : J2_7
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 40: PTB17/SPI1_MISO/LPUART0_TX/TPM_CLKIN1/SPI1_MOSI: 
**                Custom name, Signal name                 : J2_9
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 41: PTB18/TPM2_CH0                     : 
**                Custom name, Signal name                 : LEDRGB_RED/J2_11
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 42: PTB19/TPM2_CH1                     : 
**                Custom name, Signal name                 : LEDRGB_GREEN/J2_13
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 43: ADC0_SE14/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT: 
**                Custom name, Signal name                 : J4_4
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 44: ADC0_SE15/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0: 
**                Custom name, Signal name                 : BUTTON_SW3/J3_13
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 45: ADC0_SE11/PTC2/I2C1_SDA/TPM0_CH1   : 
**                Custom name, Signal name                 : ACCEL_INT2/J3_15
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 46: PTC3/LLWU_P7/SPI1_SCK/LPUART1_RX/TPM0_CH2/CLKOUT: 
**                Custom name, Signal name                 : ACCEL_INT1/J2_15
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 47: VSS53                              : 
**                Custom name, Signal name                 : VSS53
**              Pin 48: VDD54                              : 
**                Custom name, Signal name                 : VDD54
**              Pin 49: PTC4/LLWU_P8/SPI0_PCS0/LPUART1_TX/TPM0_CH3/SPI1_PCS0: 
**                Custom name, Signal name                 : J2_6
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 50: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/CMP0_OUT: 
**                Custom name, Signal name                 : J2_12
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 51: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/SPI0_MISO: 
**                Custom name, Signal name                 : J2_8
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 52: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/SPI0_MOSI: 
**                Custom name, Signal name                 : J2_10
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 53: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4    : 
**                Custom name, Signal name                 : J1_16
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 54: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5    : 
**                Custom name, Signal name                 : J1_14
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 55: PTC10/I2C1_SCL                     : 
**                Custom name, Signal name                 : J2_1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 56: PTC11/I2C1_SDA                     : 
**                Custom name, Signal name                 : J2_3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 57: PTD0/SPI0_PCS0/TPM0_CH0/FXIO0_D0   : 
**                Custom name, Signal name                 : J1_1
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 58: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1/FXIO0_D1: 
**                Custom name, Signal name                 : J1_3
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 59: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO/FXIO0_D2: 
**                Custom name, Signal name                 : J1_5
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 60: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/FXIO0_D3: 
**                Custom name, Signal name                 : J1_7
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 61: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4/FXIO0_D4: 
**                Custom name, Signal name                 : J1_9
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 62: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5/FXIO0_D5: 
**                Custom name, Signal name                 : J1_11
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 63: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/LPUART0_RX/I2C1_SDA/SPI1_MISO/FXIO0_D6: 
**                Custom name, Signal name                 : ACCEL_SDA/J2_18
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**              Pin 64: PTD7/SPI1_MISO/LPUART0_TX/I2C1_SCL/SPI1_MOSI/FXIO0_D7: 
**                Custom name, Signal name                 : ACCEL_SCL/J2_20
**                Slew rate                                : <Automatic>
**                Drive strength                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Passive filter                           : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              HAL fsl_mcglite_hal                        : fsl_mcglite_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_init.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_init_module pin_init module documentation
**  @{
*/         

/* MODULE pin_init. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_init.h"



/*FUNCTION**********************************************************************
*
* Function Name : init_adc_pins
* Description   : ADC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_adc_pins(uint32_t instance)
{
  /* Affects PORTC_PCR0 register */
  PORT_HAL_SetMuxMode(PORTC,0UL,kPortMuxAlt3);
  SIM_HAL_SetAdcTriggerMode(SIM,0,kSimAdcTrgselExt);
  SIM_HAL_SetAdcPreTriggerMode(SIM,0,kSimAdcPretrgselB);
  SIM_HAL_SetAdcAlternativeTriggerCmd(SIM,0,true);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_adc_pins
* Description   : ADC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_adc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC,0UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_coredebug_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt7);
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_coredebug_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOA_IDX:                     /* GPIOA_IDX */
      /* Affects PORTA_PCR13 register */
      PORT_HAL_SetMuxMode(PORTA,13UL,kPortMuxAsGpio);
      PORT_HAL_SetPullCmd(PORTA,13UL,true);
      break;
    case GPIOB_IDX:                     /* GPIOB_IDX */
      /* Affects PORTB_PCR18 register */
      PORT_HAL_SetMuxMode(PORTB,18UL,kPortMuxAsGpio);
      PORT_HAL_SetPullCmd(PORTB,18UL,true);
      /* Affects PORTB_PCR19 register */
      PORT_HAL_SetMuxMode(PORTB,19UL,kPortMuxAsGpio);
      PORT_HAL_SetPullCmd(PORTB,19UL,true);
      break;
    case GPIOC_IDX:                     /* GPIOC_IDX */
      /* Affects PORTC_PCR1 register */
      PORT_HAL_SetMuxMode(PORTC,1UL,kPortMuxAsGpio);
      PORT_HAL_SetPullMode(PORTC,1UL,kPortPullUp);
      PORT_HAL_SetPullCmd(PORTC,1UL,true);
      /* Affects PORTC_PCR2 register */
      PORT_HAL_SetMuxMode(PORTC,2UL,kPortMuxAsGpio);
      PORT_HAL_SetPullMode(PORTC,2UL,kPortPullUp);
      PORT_HAL_SetPullCmd(PORTC,2UL,true);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOA_IDX:                     /* GPIOA_IDX */
      PORT_HAL_SetMuxMode(PORTA,13UL,kPortPinDisabled);
      break;
    case GPIOB_IDX:                     /* GPIOB_IDX */
      PORT_HAL_SetMuxMode(PORTB,18UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTB,19UL,kPortPinDisabled);
      break;
    case GPIOC_IDX:                     /* GPIOC_IDX */
      PORT_HAL_SetMuxMode(PORTC,1UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTC,2UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}

/*FUNCTION**********************************************************************
*
* Function Name : init_llwu_pins
* Description   : LLWU method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_llwu_pins(uint32_t instance)
{
  /* Affects PORTC_PCR1 register */
  PORT_HAL_SetMuxMode(PORTC,1UL,kPortMuxAsGpio);
  PORT_HAL_SetPullMode(PORTC,1UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTC,1UL,true);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_llwu_pins
* Description   : LLWU method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_llwu_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC,1UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_osc_pins(uint32_t instance)
{
  /* Affects PORTA_PCR18 register */
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  /* Affects PORTA_PCR19 register */
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_osc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rcm_pins(uint32_t instance)
{
  /* Affects PORTA_PCR20 register */
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rcm_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_rtc_pins
* Description   : RTC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rtc_pins(uint32_t instance)
{
  /* Affects PORTC_PCR1 register */
  PORT_HAL_SetMuxMode(PORTC,1UL,kPortMuxAsGpio);
  PORT_HAL_SetPullMode(PORTC,1UL,kPortPullUp);
  PORT_HAL_SetPullCmd(PORTC,1UL,true);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rtc_pins
* Description   : RTC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rtc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTC,1UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_tpm_pins
* Description   : TPM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_tpm_pins(uint32_t instance)
{
  switch(instance) {    
    case TPM0_IDX:                      /* TPM0_IDX */
      /* Affects PORTD_PCR0 register */
      PORT_HAL_SetMuxMode(PORTD,0UL,kPortMuxAlt4);
      /* Affects PORTD_PCR1 register */
      PORT_HAL_SetMuxMode(PORTD,1UL,kPortMuxAlt4);
      break;
    case TPM1_IDX:                      /* TPM1_IDX */
      /* Affects PORTB_PCR0 register */
      PORT_HAL_SetMuxMode(PORTB,0UL,kPortMuxAlt3);
      SIM_HAL_SetTpmChSrcMode(SIM,TPM1_IDX,0,kSimTpmChSrc0);
      break;
    case TPM2_IDX:                      /* TPM2_IDX */
      /* Affects PORTB_PCR2 register */
      PORT_HAL_SetMuxMode(PORTB,2UL,kPortMuxAlt3);
      SIM_HAL_SetTpmChSrcMode(SIM,TPM2_IDX,0,kSimTpmChSrc0);  
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_tpm_pins
* Description   : TPM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_tpm_pins(uint32_t instance)
{
  switch(instance) {    
    case TPM0_IDX:                      /* TPM0_IDX */
      PORT_HAL_SetMuxMode(PORTD,0UL,kPortPinDisabled);
      PORT_HAL_SetMuxMode(PORTD,1UL,kPortPinDisabled);
      break;
    case TPM1_IDX:                      /* TPM1_IDX */
      PORT_HAL_SetMuxMode(PORTB,0UL,kPortPinDisabled);
      break;
    case TPM2_IDX:                      /* TPM2_IDX */
      PORT_HAL_SetMuxMode(PORTB,2UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}


/* END pin_init. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
